behaviors:
  car_sac:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 500000
      buffer_init_steps: 60000
      tau: 0.005
      steps_per_update: 1
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 1
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 2000000
    time_horizon: 1000
    summary_freq: 5000
    threaded: true
    framework: tensorflow
